### PR TITLE
Add ([imanghafoori1](https://github.com/imanghafoori1)) to Developers

### PR DESCRIPTION
**Pull request by erfanwd**

### CODE REVIEW

**Comment by 1995parham** [comment]
@erfanwd Can you please add your name and Github profile into the supporters' section?

**Comment by erfanwd** [comment]
@1995parham of course

**Comment by erfanwd** [comment]
@1995parham   but i'd like this account to be in developers list .
he has many stars and one of the best laravel developers in iran

**Comment by 1995parham** [comment]
I have added one of his repository, Thanks for mentioning him.

**Pull request closed without merging**
