### PR TITLE
Separate contributors file

### PR DESCRIPTION
**Pull request by chadidi**
I think it's better if we separated the contributor's file 😄

### CODE REVIEW

**Comment by MAChitgarha** [comment]
It should remain supporters, instead of converting into contributors.

**Comment by chadidi** [comment]
@1995parham hey man is this pull request mergeable so I can update it.

thanks

**Comment by pesehr** [comment]
Great Idea!
However, it's too hard to keep it up to date. We will add it after the campaign conclusion.

**Comment by chadidi** [comment]
@pesehr I was thinking that we should remove supporters list completely from the README file.

Instead, we will have on file for Supporters and All README files will link to it, this way we will have consistent similar README files.

**Comment by 1995parham** [comment]
@chadidi @pesehr I agree and then we can use #1455 to generate it based on supporters.json.

**Comment by 1995parham** [comment]
@chadidi Thanks for your contribution, because we have many changes I will do this myself right now. Again thanks for your time.

**Pull request closed without merging**
