### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JafarAkhondali**
Add list of other countries under sanctions.

### CODE REVIEW

**Comment by 1995parham** [comment]
@JafarAkhondali if you agree, I think it would be better to have another section in the README about the other countries sanction.

**Comment by JafarAkhondali** [comment]
@1995parham Not sure, IMHO it would be better to show no different between country names.

**Comment by 1995parham** [comment]
We write the sentence first time for Iranian users so I think we can provide another section and describe these issues exist for developers of other countries too.

**Comment by RezaBayat76** [comment]
That issue mentioned by @JafarAkhondali , completely valid. But with respect, in my opinion it would be better to mention these issues in another section of README.

**Comment by alisharifi2000** [comment]
Ali Sharifi 
https://github.com/alisharifi2000

**Comment by 1995parham** [comment]
@JafarAkhondali We have added the picture with these countries flag. Thank you again for all of your contributions.

**Pull request closed without merging**
