### PR TITLE
 Sort the supporters alphabetically && And me

### PR DESCRIPTION
**Pull request by MohamadKh75**
:heart:

### CODE REVIEW

**Comment by BelegCuthalion** [comment]
Thanks but you know there are ways to automate this?

**Comment by MohamadKh75** [comment]
> Thanks but you know there are ways to automate this?

Yep but I just want to add myself so I decided to sort it. we can automate it later

**Comment by pi0** [comment]
@MohamadKh75 Thanks for this PR and your support :heart:  Would you please create a fresh PR and just add your name? We can do sorting in a later PR.

**Comment by MohamadKh75** [comment]
Sure

**Pull request closed without merging**
