### PR TITLE
Adding ycombinator link, Adding my name to README.md

### PR DESCRIPTION
**Pull request by hnikaein**

### CODE REVIEW

**Comment by pesehr** [comment]
Thanks for your support and idea.
I think we have enough task for our supporters 
please remove this line:
- Upvote this thread in ycombinator: [GitHub Must Be a Free Platform](https://news.ycombinator.com/item?id=20536025)

**Comment by hnikaein** [comment]
Thanks,
But Github ignored this repository completely and not showing it on trending.
Therefore we should show this repo to others through hacker news.

**Comment by pesehr** [comment]
https://news.ycombinator.com/item?id=20531039 
So maybe this one is better

**Comment by hnikaein** [comment]
That thread is not linked to this repo.

**Pull request closed without merging**
