### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by M-Razavi**
add support

### CODE REVIEW

**Comment by 1995parham** [comment]
@M-Razavi I think you accidentally remove one of the supporters, can you please fix it?

**Comment by Adhders** [comment]
> @M-Razavi I think you accidentally remove one of the supporters, can you please fix it?

I recommit ！I close this!

**Comment by M-Razavi** [comment]
I'm sorry for that

**Comment by 1995parham** [comment]
@M-Razavi It's ok, create a new PR 🙌

**Pull request closed without merging**
