### PR TITLE
Mention Restriction Policy

### PR DESCRIPTION
**Pull request by pi0**
It is unfair to blame GitHub that they are doing restrictions based on nationality. It is clearly [stated](https://twitter.com/natfriedman/status/1155311123467399168) that restrictions are based on _place of residence and location_. It is still a good point that they analyzed the full IP access history and accidentally banning users even from outside. But they can still fill the form to get unbanned.

### CODE REVIEW

**Comment by 1995parham** [comment]
@pi0 I think we must mention that every Iranian has Iran's IP somewhere their history so Github may ban them and its a kind of ban by nationality.

**Comment by pi0** [comment]
@1195parham, would you please improve wording? I tried to use `IP address history` to mention this.

**Comment by 1995parham** [comment]
I think we can mention as P.S. I want to add it explicitly because many of contributors mention this in their messages or conversations.

**Comment by 1995parham** [comment]
@pi0 Thank you very much for this, I think we need this for being more realistic about this problem.

**Pull request merged**
